version: 2.1

jobs:
  build-arm64-native:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.medium
    steps:
      - checkout

      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            sudo usermod -aG docker $USER

      - run:
          name: Build and push ARM64 image
          command: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            docker build -t registry.cn-hangzhou.aliyuncs.com/xiak8s/shanxin-py1:arm64-latest .
            docker push registry.cn-hangzhou.aliyuncs.com/xiak8s/shanxin-py1:arm64-latest
