version: 2.1

jobs:
  build-arm64-native:
    machine:
      image: ubuntu-2204:current
      resource_class: arm.medium
    steps:
      - checkout

      - run:
          name: Install Docker
          command: |
            curl -fsSL https://get.docker.com -o get-docker.sh
            sh get-docker.sh
            sudo usermod -aG docker $USER

      - run:
          name: Build and push ARM64 image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin registry.cn-hangzhou.aliyuncs.com
            docker build -t registry.cn-hangzhou.aliyuncs.com/xiak8s/shanxin-py1:arm64-latest .
            docker push registry.cn-hangzhou.aliyuncs.com/xiak8s/shanxin-py1:arm64-latest

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-arm64-native
